### PR TITLE
add write methods

### PR DESCRIPTION
**Pull request by Rintse**
I figured out a bunch of the logic to do a couple of write methods.
I am not good at rust.

Hopefully my efforts are useful somehow.
I will leave this here.

### CODE REVIEW

**Comment by dzfranklin** [comment]
This looks cool! I'm no longer maintaining this library. If you end up polishing this I'd be happy to hand the library over to you.

**Comment by Rintse** [comment]
Cool.
In that case I will try to get this as ready as I can for the outside world.
Will get back to you.

**Comment by Rintse** [comment]
I think my branch is now relatively clean and somewhat tested.

~~There still are a bunch of memory leaks which I will fix at some point, but leaving those aside for now:~~
What would be the next steps?

Is it maybe best if I publish this on my own and take over the crate, rather than actually have this as a pull request.

**Comment by dzfranklin** [comment]
If this is gonna be under my name I'd like to read through all the changes, but it'll be a little while before I'm free. We could also transfer ownership to you.

**Comment by Rintse** [comment]
The latter makes more sense to me.

**Comment by dzfranklin** [comment]
What's your crates.io username?

**Comment by Rintse** [comment]
> 

That would be Rintse as well.
Do I not just use my own repo? I see you invited me.

**Comment by dzfranklin** [comment]
If you want to publish an update to the existing crate you'd need to be added to crates.io. Rintse gave me a user not found error.

**Comment by Rintse** [comment]
Yeah I just registered earlier today. Could be it needs some time to propegate or sth.

**Comment by dzfranklin** [comment]
is this done?

**Comment by Rintse** [comment]
I have not found time to look at the proper way to take over the crate.

I was thinking I'd just `cargo publish` from my repo with an updated version in the `Cargo.toml`.

But maybe I should make an entirely new repo?
Or use this one?


Maybe you have thoughts?

**Comment by dzfranklin** [comment]
You've got write access to this repo and publish access to the crate.

So you can merge your own PR into this repo and then publish this repo if you want

**Comment by Rintse** [comment]
@danielzfranklin I just now realised that the description still says that only read methods are present.

I do not have the rights to alter this. Could you update it?

**Comment by dzfranklin** [comment]
Done. Should I take off the WIP as well?

**Comment by Rintse** [comment]
> Done. Should I take off the WIP as well?

Thanks! I think WIP still fits pretty well ;)

**Pull request merged**
